Cosmology:
  H0: 70
  Omega_m: 0.3

Siminfo:
  Boxsize: 75.
  Ngrid: 256

#Particles: Null
  # Type: NPZ #Gadget or NPZ
  # Filelist: Null #lv_fname_npz.txt
  # Fileprefix: levy_flight_sim_
  # Filesuffix: .npz
  # Nfiles: 1
  # # # # # if ascii
  # # # ASCII_Columns: [0, 1, 2]
  # NPZ_Keys: ["x", "y", "z"]
  # # Type: Gadget
  # # Filelist: Null
  # # Fname: test_lustre_cons_z0p000
  # # Nfiles: 4
  # # Pos_Factor: 1

#Density: Null
  # # # # Type: TSC
  # # # # Saveas: dens_lf_TSC
  # Type: DTFE
  # MPI_Split: 4
  # Buffer_Type: periodic
  # Buffer_Length: 20.
  # Subsampling: 10
  # Saveas: dens_lf_DTFE_

CosmicWeb:
  Density_Prefix: dens_lf_DTFE_
  Density_Nfiles: 4
  # Filter:
  #   Type: Tophat
  #   R: 0.5
  Type: Tweb
  Tweb:
    Threshold: 0.2
    Output: cweb_tweb_env_
  # Type: Nexus
  # Nexus:
  #   # Signature:
  #   #   R0: 0.5
  #   #   Nmax: 1
  #   #   Logsmooth: [False, True, True]
  #   #   Output: cweb_nexus_sig2_
  #   Thresholds:
  #     SigFile:
  #       Prefix: cweb_nexus_sig_
  #       Nfiles: 4
  #     Clusters:
  #       Minvirdens: 220
  #       Nbins: 100 #make as default, without necessitating definition
  #       Evaluate: 20 # ditto
  #       Minpix: 100
  #     Filaments:
  #       Nbins: 100
  #       Minpix: 100
  #     Walls:
  #       Nbins: 100
  #       Minpix: 100
  #     Output: cweb_nexus_env_
